/* ═══════════════════════════════════════════════════════════════
   KITS DE NICHO — bases pré-moldadas usadas pelo admin.html.
   Na primeira vez que o admin abre, estes kits são gravados na
   tabela "kits" do Supabase; depois disso o que vale é o banco.
   {{variavel}} é substituída pelos dados de cada empresa.
   ═══════════════════════════════════════════════════════════════ */
const VARS_COMUNS = [
  {k:'empresa',label:'Nome da empresa',ex:'Minha Empresa'},
  {k:'horario',label:'Horário de funcionamento',ex:'segunda a sexta das 9h às 18h e sábado das 9h às 13h'},
  {k:'endereco',label:'Endereço',ex:'Rua Exemplo, 123 – Centro'},
  {k:'telefone',label:'Telefone',ex:'(00) 0000-0000'},
  {k:'whatsapp',label:'WhatsApp',ex:'(00) 90000-0000'},
  {k:'pagamento',label:'Formas de pagamento',ex:'Pix, dinheiro, cartão de débito e crédito'},
];
const ENT_COMUNS = [
  {intencao:'horario',categoria:'Informações',perguntas:['qual o horário de funcionamento','que horas abre','que horas fecha','vocês abrem sábado','estão abertos hoje','abre domingo','funciona feriado'],resposta:'Nosso horário de atendimento é {{horario}} 🕐'},
  {intencao:'endereco',categoria:'Informações',perguntas:['onde fica a loja','qual o endereço','como chego aí','localização','onde vocês ficam','manda a localização'],resposta:'Estamos em {{endereco}} 📍\nSe precisar, é só chamar no {{whatsapp}}.'},
  {intencao:'contato',categoria:'Informações',perguntas:['qual o telefone','número do whatsapp','tem instagram','como entro em contato','qual o contato'],resposta:'Você pode falar com a gente pelo telefone {{telefone}} ou WhatsApp {{whatsapp}} 📞'},
  {intencao:'atendente_humano',categoria:'Atendimento',perguntas:['quero falar com atendente','falar com uma pessoa','atendimento humano','chama alguém','quero falar com o dono','tem alguém aí'],resposta:'Claro! Já avisei nossa equipe e alguém continua o atendimento com você em instantes 🙋 (atendimento humano: {{horario}}).',humano:true},
  {intencao:'pagamento',categoria:'Pagamento',perguntas:['quais as formas de pagamento','aceita cartão','aceita pix','aceita dinheiro','posso pagar no débito','como posso pagar'],resposta:'Aceitamos {{pagamento}} 💳'},
];
const KITS_PADRAO = {
  servicos:{
    id:'servicos',nome:'Serviços / Assistência técnica',icone:'🔧',
    descricao:'Assistências técnicas, consertos, manutenção e prestadores de serviço.',
    modulos:['Agendamento e atendimento sem hora marcada','Orçamentos básicos e preços de referência','Status de ordem de serviço','Garantia, prazos, localização e horários'],
    vars:[...VARS_COMUNS,
      {k:'servicos',label:'Serviços oferecidos',ex:'conserto de celulares, tablets e notebooks, troca de tela e bateria, desbloqueio e limpeza'},
      {k:'taxa_diagnostico',label:'Taxa de orçamento/diagnóstico',ex:'o orçamento é gratuito'},
      {k:'prazo_orcamento',label:'Prazo do orçamento',ex:'até 24 horas úteis'},
      {k:'prazo_reparo',label:'Prazo médio do reparo',ex:'A maioria dos reparos fica pronta em 1 a 3 dias úteis; troca de tela costuma sair no mesmo dia.'},
      {k:'garantia',label:'Garantia',ex:'90 dias'},
      {k:'preco_tela',label:'Preço de referência – tela',ex:'A troca de tela sai a partir de R$ 180.'},
      {k:'preco_bateria',label:'Preço de referência – bateria',ex:'A troca de bateria sai a partir de R$ 120.'},
      {k:'acessorios',label:'Acessórios à venda',ex:'Temos capinhas, películas, carregadores e fones 🎧'},
    ],
    saudacao:'Olá! 👋 Aqui é o assistente virtual da {{empresa}}. Posso te ajudar com orçamentos, prazos, garantia, status do seu aparelho e mais. O que você precisa?',
    entradas:[...ENT_COMUNS,
      {intencao:'orcamento',categoria:'Orçamento',perguntas:['quanto custa o conserto','fazem orçamento','quanto fica para arrumar','preço do reparo','orçamento é grátis','quanto cobra para consertar'],resposta:'Fazemos orçamento sim! Na {{empresa}} {{taxa_diagnostico}}, com prazo de {{prazo_orcamento}}.\nMe diga *marca, modelo e defeito* do aparelho que já adiantamos uma estimativa 😉'},
      {intencao:'troca_tela',categoria:'Serviços',perguntas:['troca de tela','tela quebrada','trocar display','quanto é a tela','tela trincada','tela não liga'],resposta:'{{preco_tela}} O valor final depende do modelo — me diga a marca e o modelo do aparelho 📱'},
      {intencao:'bateria',categoria:'Serviços',perguntas:['troca de bateria','bateria viciada','celular descarregando rápido','bateria estufada','bateria não segura carga'],resposta:'{{preco_bateria}} Se a bateria estiver estufada, evite carregar o aparelho e traga assim que possível ⚠️'},
      {intencao:'prazo_reparo',categoria:'Prazos',perguntas:['quanto tempo demora o conserto','fica pronto hoje','quando fica pronto','prazo do conserto','demora quantos dias'],resposta:'{{prazo_reparo}}'},
      {intencao:'status_os',categoria:'Ordem de serviço',perguntas:['meu aparelho já está pronto','status do conserto','consultar ordem de serviço','andamento do meu conserto','já posso buscar meu celular'],resposta:'Para consultar sua ordem de serviço, me envie o *número da OS* ou o *CPF* cadastrado que nossa equipe confirma o status para você 🔧',humano:true},
      {intencao:'garantia',categoria:'Garantia',perguntas:['tem garantia','quanto tempo de garantia','garantia do serviço','deu problema de novo','voltou o defeito'],resposta:'Todos os nossos serviços têm garantia de {{garantia}} ✅ Se o defeito voltar dentro desse prazo, traga o aparelho com a OS que avaliamos sem custo.'},
      {intencao:'agendamento',categoria:'Atendimento',perguntas:['quero agendar','marcar horário','precisa agendar','atende sem agendamento','posso levar agora'],resposta:'Não precisa agendar! É só trazer o aparelho dentro do horário ({{horario}}). Se preferir, me diga o melhor dia e horário que deixamos reservado 🗓️'},
      {intencao:'servicos',categoria:'Serviços',perguntas:['quais serviços vocês fazem','consertam notebook','arrumam tablet','fazem desbloqueio','vocês consertam'],resposta:'Trabalhamos com {{servicos}}.'},
      {intencao:'dados_backup',categoria:'Serviços',perguntas:['vou perder meus dados','vou perder as fotos','fazem backup','apaga tudo do celular'],resposta:'Na maioria dos reparos seus dados são preservados 👍 Mesmo assim, recomendamos fazer backup antes. Se precisar, nossa equipe pode ajudar com isso.'},
      {intencao:'molhou',categoria:'Serviços',perguntas:['celular caiu na água','celular molhou','oxidação','caiu na piscina','entrou água'],resposta:'Desligue o aparelho agora, não coloque para carregar e não coloque no arroz 🙏 Traga o quanto antes para {{endereco}} — quanto mais rápido, maiores as chances de recuperação.'},
      {intencao:'acessorios',categoria:'Produtos',perguntas:['vende capinha','tem película','vende carregador','tem fone de ouvido','acessórios'],resposta:'{{acessorios}}'},
    ]
  },
  comercio:{
    id:'comercio',nome:'Comércio / Lojas',icone:'🛍️',
    descricao:'Lojas de varejo, moda, calçados, presentes e comércio em geral.',
    modulos:['Catálogo de produtos e preços','Consulta de estoque (com encaminhamento)','Formas de pagamento, parcelamento e links de checkout','Frete, retirada, trocas e rastreio'],
    vars:[...VARS_COMUNS,
      {k:'link_catalogo',label:'Link do catálogo/loja',ex:'https://minhaloja.com.br'},
      {k:'parcelamento',label:'Parcelamento',ex:'Parcelamos em até 6x sem juros no cartão (parcela mínima de R$ 50).'},
      {k:'frete',label:'Frete',ex:'Entregamos na cidade com taxa a partir de R$ 8 e enviamos para todo o Brasil pelos Correios.'},
      {k:'prazo_entrega',label:'Prazo de entrega',ex:'Na cidade entregamos em até 1 dia útil; pelos Correios o prazo é de 3 a 10 dias úteis.'},
      {k:'retirada',label:'Retirada na loja',ex:'Sim! Você pode comprar online e retirar na loja no mesmo dia, sem custo.'},
      {k:'politica_troca',label:'Política de troca',ex:'As trocas podem ser feitas em até 30 dias com a etiqueta e a nota fiscal.'},
      {k:'promocoes',label:'Promoções vigentes',ex:'Estamos com 10% de desconto no Pix em toda a loja 🎉'},
    ],
    saudacao:'Oi! 👋 Bem-vindo(a) à {{empresa}}. Posso te ajudar com produtos, preços, formas de pagamento, entregas e trocas. O que você procura hoje?',
    entradas:[...ENT_COMUNS,
      {intencao:'catalogo',categoria:'Produtos',perguntas:['tem catálogo','quero ver os produtos','quais produtos vocês têm','me manda as fotos','link da loja','novidades da semana'],resposta:'Confira nosso catálogo completo aqui: {{link_catalogo}} 🛍️'},
      {intencao:'estoque',categoria:'Produtos',perguntas:['tem esse produto','tem no tamanho m','ainda tem disponível','chegou reposição','tem em estoque','tem outra cor'],resposta:'Me diga o *produto* (ou envie a foto/código), *tamanho* e *cor* que eu verifico a disponibilidade com a equipe 😉',humano:true},
      {intencao:'preco',categoria:'Produtos',perguntas:['quanto custa','qual o valor','preço da peça','tá quanto','valor do produto'],resposta:'Os preços atualizados estão no catálogo: {{link_catalogo}}. Se preferir, me mande o nome ou a foto do produto que confirmo o valor 💬'},
      {intencao:'parcelamento',categoria:'Pagamento',perguntas:['parcela em quantas vezes','parcelamento sem juros','divide no cartão','pode parcelar'],resposta:'{{parcelamento}}'},
      {intencao:'frete',categoria:'Entrega',perguntas:['quanto é o frete','valor do frete','entrega na minha cidade','fazem entrega','envia pelos correios','entregam em casa'],resposta:'{{frete}}'},
      {intencao:'prazo_entrega',categoria:'Entrega',perguntas:['quanto tempo chega','prazo de entrega','quando chega meu pedido','demora para chegar'],resposta:'{{prazo_entrega}}'},
      {intencao:'retirada',categoria:'Entrega',perguntas:['posso retirar na loja','retirar pessoalmente','buscar na loja','compro online e retiro'],resposta:'{{retirada}} Endereço: {{endereco}}.'},
      {intencao:'troca',categoria:'Pós-venda',perguntas:['posso trocar','política de troca','não serviu','devolução','trocar tamanho','quero devolver'],resposta:'{{politica_troca}} É só trazer na loja ou chamar a gente por aqui 🔄'},
      {intencao:'rastreio',categoria:'Pós-venda',perguntas:['rastrear pedido','código de rastreio','cadê meu pedido','meu pedido não chegou'],resposta:'Para rastrear, me envie o *número do pedido* ou o *CPF* da compra que nossa equipe te passa o status 📦',humano:true},
      {intencao:'promocao',categoria:'Vendas',perguntas:['tem promoção','tem desconto','tem cupom','liquidação','black friday'],resposta:'{{promocoes}}'},
      {intencao:'comprar',categoria:'Vendas',perguntas:['como faço para comprar','quero comprar','finalizar pedido','manda o link de pagamento','quero fechar o pedido'],resposta:'É fácil! Você pode comprar direto pelo {{link_catalogo}} ou me dizer aqui o produto, tamanho e cor que geramos o link de pagamento 💳'},
      {intencao:'nota_fiscal',categoria:'Pós-venda',perguntas:['emite nota fiscal','preciso da nota','manda a nota fiscal'],resposta:'Sim, emitimos nota fiscal em todas as compras 🧾 Se precisar de uma segunda via, me envie o número do pedido.'},
    ]
  },
  alimentacao:{
    id:'alimentacao',nome:'Alimentação / Delivery',icone:'🍔',
    descricao:'Restaurantes, lanchonetes, pizzarias, docerias e delivery.',
    modulos:['Cardápio, sabores e opções especiais','Pedidos, taxa, área e tempo de entrega','Promoções, combos e encomendas','Suporte pós-venda e reclamações'],
    vars:[...VARS_COMUNS,
      {k:'link_cardapio',label:'Link do cardápio',ex:'https://cardapio.exemplo.com.br'},
      {k:'taxa_entrega',label:'Taxa de entrega',ex:'A taxa de entrega é de R$ 5 no centro e R$ 8 nos demais bairros.'},
      {k:'area_entrega',label:'Área de entrega',ex:'Entregamos em toda a área urbana da cidade.'},
      {k:'tempo_entrega',label:'Tempo de entrega',ex:'O tempo médio de entrega é de 40 a 60 minutos (pode variar nos horários de pico).'},
      {k:'pedido_minimo',label:'Pedido mínimo',ex:'O pedido mínimo para entrega é de R$ 25.'},
      {k:'promocoes',label:'Promoções e combos',ex:'Terça é dia de pizza em dobro 🍕 e todos os dias temos combo com refri por R$ 39,90.'},
      {k:'opcoes_especiais',label:'Opções especiais',ex:'Temos opções vegetarianas e sem lactose. Pratos sem glúten sob consulta.'},
      {k:'encomendas',label:'Encomendas',ex:'Aceitamos encomendas para festas com 48h de antecedência.'},
    ],
    saudacao:'Olá! 😋 Aqui é o assistente da {{empresa}}. Posso te mostrar o cardápio, taxas e tempo de entrega, promoções ou anotar seu pedido. Como posso ajudar?',
    entradas:[...ENT_COMUNS,
      {intencao:'cardapio',categoria:'Cardápio',perguntas:['cardápio','manda o menu','o que tem hoje','quais os sabores','quais as opções','tem lanche'],resposta:'Nosso cardápio completo está aqui: {{link_cardapio}} 😋'},
      {intencao:'fazer_pedido',categoria:'Pedidos',perguntas:['quero fazer um pedido','como faço para pedir','pedir pelo whatsapp','quero pedir','anota meu pedido'],resposta:'Bora! Você pode pedir pelo {{link_cardapio}} ou me mandar aqui: *itens*, *endereço de entrega* e *forma de pagamento* que eu passo direto para a cozinha 👨‍🍳',humano:true},
      {intencao:'taxa_entrega',categoria:'Entrega',perguntas:['qual a taxa de entrega','quanto é a entrega','tem frete grátis','valor da entrega'],resposta:'{{taxa_entrega}}'},
      {intencao:'area_entrega',categoria:'Entrega',perguntas:['entrega no meu bairro','até onde vocês entregam','atende minha região','entrega no bairro'],resposta:'{{area_entrega}} Se quiser, me diga seu bairro que eu confirmo 😉'},
      {intencao:'tempo_entrega',categoria:'Entrega',perguntas:['quanto tempo demora','tempo de entrega','demora muito','previsão de chegada','quanto tempo chega'],resposta:'{{tempo_entrega}} 🛵'},
      {intencao:'status_pedido',categoria:'Pedidos',perguntas:['cadê meu pedido','meu pedido já saiu','pedido atrasado','já está vindo','meu lanche não chegou'],resposta:'Vou verificar com a cozinha agora! Me informe seu *nome* ou o *número do pedido* 🛵',humano:true},
      {intencao:'pedido_minimo',categoria:'Pedidos',perguntas:['tem pedido mínimo','qual o valor mínimo','valor mínimo para entrega'],resposta:'{{pedido_minimo}}'},
      {intencao:'retirada',categoria:'Entrega',perguntas:['posso retirar no local','retirar no balcão','posso buscar aí','retirada'],resposta:'Pode sim! É só fazer o pedido e retirar em {{endereco}} 🥡'},
      {intencao:'promocao',categoria:'Vendas',perguntas:['promoção do dia','tem combo','tem desconto','tem cupom','promoção de hoje'],resposta:'{{promocoes}}'},
      {intencao:'restricoes',categoria:'Cardápio',perguntas:['tem opção vegana','sem glúten','sem lactose','tem vegetariano','tenho alergia'],resposta:'{{opcoes_especiais}} Em caso de alergia, avise no pedido para a cozinha tomar os cuidados necessários 🙏'},
      {intencao:'reclamacao',categoria:'Pós-venda',perguntas:['veio errado','pedido veio frio','faltou item','quero reclamar','veio faltando'],resposta:'Sinto muito por isso 😔 Me envie o *número do pedido* e uma foto, se possível, que nossa equipe resolve com prioridade.',humano:true},
      {intencao:'encomenda',categoria:'Vendas',perguntas:['aceita encomenda','pedido para festa','bolo por encomenda','pedido para evento'],resposta:'{{encomendas}}'},
    ]
  }
};
